<?php

namespace ApiBundle\Repository;

/**
 * FoodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoodRepository extends \Doctrine\ORM\EntityRepository
{

    public function getBySearch($search)
    {
        return $this->createQueryBuilder('f')
                    ->where('f.origgpfr LIKE :search')
                    ->orWhere('f.origfdnm LIKE :search')
                    ->setParameter('search', '%'.$search.'%')
                    ->getQuery()
                    ->getResult();
    }
}
